### ISSUE TITLE
Probably wrong documentation for `lpf_collectives_init`

### ISSUE THREAD

**Issue by alberto-scolari** [Algebraic-Programming/LPF#11]
The documentation says the the parameter `max_calls` of `lpf_collectives_init` must be larger than 0

https://github.com/Algebraic-Programming/LPF/blob/436b7d3d8d66fbaca0fef40cd20ab99952c3cc1a/include/lpf/collectives.h#L135-L137

but in ALP it is used successfully as 0 (tested !)

https://github.com/Algebraic-Programming/ALP/blob/b50fe72e957ed4da10c1cd1c59d924260f051a8d/include/graphblas/bsp1d/exec.hpp#L67

and indeed the implementation ignores it

https://github.com/Algebraic-Programming/LPF/blob/436b7d3d8d66fbaca0fef40cd20ab99952c3cc1a/src/core-libraries/collectives.c#L88

Should the documentation be changed?

**Comment by anyzelman** [comment]
The doc (spec) is OK, it's ALP that should fix it, even if the implementation happens to be ok with it.

I was briefly considering returning an error, but LPF does typically not guard against trivial errors (nor any type of errors) by its philosophy. We could introduce an `ILLEGAL` error code for higher-level libraries, but then such libraries are probably better placed outside the LPF repo. So doing nothing here seems best.

Anyway, creating an issue on the ALP repo: number 249 (https://github.com/Algebraic-Programming/ALP/issues/249) and closing this one.
