### ISSUE TITLE
Engine-specific tests by design

### ISSUE THREAD

**Issue by KADichev** [Algebraic-Programming/LPF#29]
Some tests are designed for specific engines, see following:

    func_lpf_debug_hook_null_f_symbols.pthread.cpp
    func_lpf_debug_hook_null_input.pthread.cpp
    func_lpf_debug_hook_null_output.pthread.cpp
    func_lpf_debug_hook_null_spmd.pthread.cpp

As part of https://github.com/Algebraic-Programming/LPF/pull/26 these tests are now commented, that is only a minor thing to fix though compared to the rest.

**Comment by anyzelman** [comment]
Tests are fixed and enabled as part of #26
